namespace Feliz.MaterialUI

(*////////////////////////////////
/// THIS FILE IS AUTO-GENERATED //
////////////////////////////////*)

open System.ComponentModel
open Fable.Core
open Fable.Core.JsInterop
open Feliz


[<AutoOpen; EditorBrowsable(EditorBrowsableState.Never)>]
module themeProps =

  module theme =

    [<Erase>]
    type props =
      static member inline muiAccordion(props: IReactProperty list) : IThemeProp = unbox ("props.MuiAccordion", createObj !!props)
      static member inline muiAccordionActions(props: IReactProperty list) : IThemeProp = unbox ("props.MuiAccordionActions", createObj !!props)
      static member inline muiAccordionDetails(props: IReactProperty list) : IThemeProp = unbox ("props.MuiAccordionDetails", createObj !!props)
      static member inline muiAccordionSummary(props: IReactProperty list) : IThemeProp = unbox ("props.MuiAccordionSummary", createObj !!props)
      static member inline muiAlert(props: IReactProperty list) : IThemeProp = unbox ("props.MuiAlert", createObj !!props)
      static member inline muiAlertTitle(props: IReactProperty list) : IThemeProp = unbox ("props.MuiAlertTitle", createObj !!props)
      static member inline muiAppBar(props: IReactProperty list) : IThemeProp = unbox ("props.MuiAppBar", createObj !!props)
      static member inline muiAutocomplete(props: IReactProperty list) : IThemeProp = unbox ("props.MuiAutocomplete", createObj !!props)
      static member inline muiAvatar(props: IReactProperty list) : IThemeProp = unbox ("props.MuiAvatar", createObj !!props)
      static member inline muiAvatarGroup(props: IReactProperty list) : IThemeProp = unbox ("props.MuiAvatarGroup", createObj !!props)
      static member inline muiBackdrop(props: IReactProperty list) : IThemeProp = unbox ("props.MuiBackdrop", createObj !!props)
      static member inline muiBadge(props: IReactProperty list) : IThemeProp = unbox ("props.MuiBadge", createObj !!props)
      static member inline muiBottomNavigation(props: IReactProperty list) : IThemeProp = unbox ("props.MuiBottomNavigation", createObj !!props)
      static member inline muiBottomNavigationAction(props: IReactProperty list) : IThemeProp = unbox ("props.MuiBottomNavigationAction", createObj !!props)
      static member inline muiBreadcrumbs(props: IReactProperty list) : IThemeProp = unbox ("props.MuiBreadcrumbs", createObj !!props)
      static member inline muiButton(props: IReactProperty list) : IThemeProp = unbox ("props.MuiButton", createObj !!props)
      static member inline muiButtonBase(props: IReactProperty list) : IThemeProp = unbox ("props.MuiButtonBase", createObj !!props)
      static member inline muiButtonGroup(props: IReactProperty list) : IThemeProp = unbox ("props.MuiButtonGroup", createObj !!props)
      static member inline muiCard(props: IReactProperty list) : IThemeProp = unbox ("props.MuiCard", createObj !!props)
      static member inline muiCardActionArea(props: IReactProperty list) : IThemeProp = unbox ("props.MuiCardActionArea", createObj !!props)
      static member inline muiCardActions(props: IReactProperty list) : IThemeProp = unbox ("props.MuiCardActions", createObj !!props)
      static member inline muiCardContent(props: IReactProperty list) : IThemeProp = unbox ("props.MuiCardContent", createObj !!props)
      static member inline muiCardHeader(props: IReactProperty list) : IThemeProp = unbox ("props.MuiCardHeader", createObj !!props)
      static member inline muiCardMedia(props: IReactProperty list) : IThemeProp = unbox ("props.MuiCardMedia", createObj !!props)
      static member inline muiCheckbox(props: IReactProperty list) : IThemeProp = unbox ("props.MuiCheckbox", createObj !!props)
      static member inline muiChip(props: IReactProperty list) : IThemeProp = unbox ("props.MuiChip", createObj !!props)
      static member inline muiCircularProgress(props: IReactProperty list) : IThemeProp = unbox ("props.MuiCircularProgress", createObj !!props)
      static member inline muiClickAwayListener(props: IReactProperty list) : IThemeProp = unbox ("props.MuiClickAwayListener", createObj !!props)
      static member inline muiCollapse(props: IReactProperty list) : IThemeProp = unbox ("props.MuiCollapse", createObj !!props)
      static member inline muiContainer(props: IReactProperty list) : IThemeProp = unbox ("props.MuiContainer", createObj !!props)
      static member inline muiCssBaseline(props: IReactProperty list) : IThemeProp = unbox ("props.MuiCssBaseline", createObj !!props)
      static member inline muiDialog(props: IReactProperty list) : IThemeProp = unbox ("props.MuiDialog", createObj !!props)
      static member inline muiDialogActions(props: IReactProperty list) : IThemeProp = unbox ("props.MuiDialogActions", createObj !!props)
      static member inline muiDialogContent(props: IReactProperty list) : IThemeProp = unbox ("props.MuiDialogContent", createObj !!props)
      static member inline muiDialogContentText(props: IReactProperty list) : IThemeProp = unbox ("props.MuiDialogContentText", createObj !!props)
      static member inline muiDialogTitle(props: IReactProperty list) : IThemeProp = unbox ("props.MuiDialogTitle", createObj !!props)
      static member inline muiDivider(props: IReactProperty list) : IThemeProp = unbox ("props.MuiDivider", createObj !!props)
      static member inline muiDrawer(props: IReactProperty list) : IThemeProp = unbox ("props.MuiDrawer", createObj !!props)
      static member inline muiExpansionPanel(props: IReactProperty list) : IThemeProp = unbox ("props.MuiExpansionPanel", createObj !!props)
      static member inline muiExpansionPanelActions(props: IReactProperty list) : IThemeProp = unbox ("props.MuiExpansionPanelActions", createObj !!props)
      static member inline muiExpansionPanelDetails(props: IReactProperty list) : IThemeProp = unbox ("props.MuiExpansionPanelDetails", createObj !!props)
      static member inline muiExpansionPanelSummary(props: IReactProperty list) : IThemeProp = unbox ("props.MuiExpansionPanelSummary", createObj !!props)
      static member inline muiFab(props: IReactProperty list) : IThemeProp = unbox ("props.MuiFab", createObj !!props)
      static member inline muiFade(props: IReactProperty list) : IThemeProp = unbox ("props.MuiFade", createObj !!props)
      static member inline muiFilledInput(props: IReactProperty list) : IThemeProp = unbox ("props.MuiFilledInput", createObj !!props)
      static member inline muiFormControl(props: IReactProperty list) : IThemeProp = unbox ("props.MuiFormControl", createObj !!props)
      static member inline muiFormControlLabel(props: IReactProperty list) : IThemeProp = unbox ("props.MuiFormControlLabel", createObj !!props)
      static member inline muiFormGroup(props: IReactProperty list) : IThemeProp = unbox ("props.MuiFormGroup", createObj !!props)
      static member inline muiFormHelperText(props: IReactProperty list) : IThemeProp = unbox ("props.MuiFormHelperText", createObj !!props)
      static member inline muiFormLabel(props: IReactProperty list) : IThemeProp = unbox ("props.MuiFormLabel", createObj !!props)
      static member inline muiGrid(props: IReactProperty list) : IThemeProp = unbox ("props.MuiGrid", createObj !!props)
      static member inline muiGridList(props: IReactProperty list) : IThemeProp = unbox ("props.MuiGridList", createObj !!props)
      static member inline muiGridListTile(props: IReactProperty list) : IThemeProp = unbox ("props.MuiGridListTile", createObj !!props)
      static member inline muiGridListTileBar(props: IReactProperty list) : IThemeProp = unbox ("props.MuiGridListTileBar", createObj !!props)
      static member inline muiGrow(props: IReactProperty list) : IThemeProp = unbox ("props.MuiGrow", createObj !!props)
      static member inline muiHidden(props: IReactProperty list) : IThemeProp = unbox ("props.MuiHidden", createObj !!props)
      static member inline muiIcon(props: IReactProperty list) : IThemeProp = unbox ("props.MuiIcon", createObj !!props)
      static member inline muiIconButton(props: IReactProperty list) : IThemeProp = unbox ("props.MuiIconButton", createObj !!props)
      static member inline muiInput(props: IReactProperty list) : IThemeProp = unbox ("props.MuiInput", createObj !!props)
      static member inline muiInputAdornment(props: IReactProperty list) : IThemeProp = unbox ("props.MuiInputAdornment", createObj !!props)
      static member inline muiInputBase(props: IReactProperty list) : IThemeProp = unbox ("props.MuiInputBase", createObj !!props)
      static member inline muiInputLabel(props: IReactProperty list) : IThemeProp = unbox ("props.MuiInputLabel", createObj !!props)
      static member inline muiLinearProgress(props: IReactProperty list) : IThemeProp = unbox ("props.MuiLinearProgress", createObj !!props)
      static member inline muiLink(props: IReactProperty list) : IThemeProp = unbox ("props.MuiLink", createObj !!props)
      static member inline muiList(props: IReactProperty list) : IThemeProp = unbox ("props.MuiList", createObj !!props)
      static member inline muiListItem(props: IReactProperty list) : IThemeProp = unbox ("props.MuiListItem", createObj !!props)
      static member inline muiListItemAvatar(props: IReactProperty list) : IThemeProp = unbox ("props.MuiListItemAvatar", createObj !!props)
      static member inline muiListItemIcon(props: IReactProperty list) : IThemeProp = unbox ("props.MuiListItemIcon", createObj !!props)
      static member inline muiListItemSecondaryAction(props: IReactProperty list) : IThemeProp = unbox ("props.MuiListItemSecondaryAction", createObj !!props)
      static member inline muiListItemText(props: IReactProperty list) : IThemeProp = unbox ("props.MuiListItemText", createObj !!props)
      static member inline muiListSubheader(props: IReactProperty list) : IThemeProp = unbox ("props.MuiListSubheader", createObj !!props)
      static member inline muiMenu(props: IReactProperty list) : IThemeProp = unbox ("props.MuiMenu", createObj !!props)
      static member inline muiMenuItem(props: IReactProperty list) : IThemeProp = unbox ("props.MuiMenuItem", createObj !!props)
      static member inline muiMenuList(props: IReactProperty list) : IThemeProp = unbox ("props.MuiMenuList", createObj !!props)
      static member inline muiMobileStepper(props: IReactProperty list) : IThemeProp = unbox ("props.MuiMobileStepper", createObj !!props)
      static member inline muiModal(props: IReactProperty list) : IThemeProp = unbox ("props.MuiModal", createObj !!props)
      static member inline muiNativeSelect(props: IReactProperty list) : IThemeProp = unbox ("props.MuiNativeSelect", createObj !!props)
      static member inline muiNoSsr(props: IReactProperty list) : IThemeProp = unbox ("props.MuiNoSsr", createObj !!props)
      static member inline muiOutlinedInput(props: IReactProperty list) : IThemeProp = unbox ("props.MuiOutlinedInput", createObj !!props)
      static member inline muiPagination(props: IReactProperty list) : IThemeProp = unbox ("props.MuiPagination", createObj !!props)
      static member inline muiPaginationItem(props: IReactProperty list) : IThemeProp = unbox ("props.MuiPaginationItem", createObj !!props)
      static member inline muiPaper(props: IReactProperty list) : IThemeProp = unbox ("props.MuiPaper", createObj !!props)
      static member inline muiPopover(props: IReactProperty list) : IThemeProp = unbox ("props.MuiPopover", createObj !!props)
      static member inline muiPopper(props: IReactProperty list) : IThemeProp = unbox ("props.MuiPopper", createObj !!props)
      static member inline muiPortal(props: IReactProperty list) : IThemeProp = unbox ("props.MuiPortal", createObj !!props)
      static member inline muiRadio(props: IReactProperty list) : IThemeProp = unbox ("props.MuiRadio", createObj !!props)
      static member inline muiRadioGroup(props: IReactProperty list) : IThemeProp = unbox ("props.MuiRadioGroup", createObj !!props)
      static member inline muiRating(props: IReactProperty list) : IThemeProp = unbox ("props.MuiRating", createObj !!props)
      static member inline muiRootRef(props: IReactProperty list) : IThemeProp = unbox ("props.MuiRootRef", createObj !!props)
      static member inline muiScopedCssBaseline(props: IReactProperty list) : IThemeProp = unbox ("props.MuiScopedCssBaseline", createObj !!props)
      static member inline muiSelect(props: IReactProperty list) : IThemeProp = unbox ("props.MuiSelect", createObj !!props)
      static member inline muiSkeleton(props: IReactProperty list) : IThemeProp = unbox ("props.MuiSkeleton", createObj !!props)
      static member inline muiSlide(props: IReactProperty list) : IThemeProp = unbox ("props.MuiSlide", createObj !!props)
      static member inline muiSlider(props: IReactProperty list) : IThemeProp = unbox ("props.MuiSlider", createObj !!props)
      static member inline muiSnackbar(props: IReactProperty list) : IThemeProp = unbox ("props.MuiSnackbar", createObj !!props)
      static member inline muiSnackbarContent(props: IReactProperty list) : IThemeProp = unbox ("props.MuiSnackbarContent", createObj !!props)
      static member inline muiSpeedDial(props: IReactProperty list) : IThemeProp = unbox ("props.MuiSpeedDial", createObj !!props)
      static member inline muiSpeedDialAction(props: IReactProperty list) : IThemeProp = unbox ("props.MuiSpeedDialAction", createObj !!props)
      static member inline muiSpeedDialIcon(props: IReactProperty list) : IThemeProp = unbox ("props.MuiSpeedDialIcon", createObj !!props)
      static member inline muiStep(props: IReactProperty list) : IThemeProp = unbox ("props.MuiStep", createObj !!props)
      static member inline muiStepButton(props: IReactProperty list) : IThemeProp = unbox ("props.MuiStepButton", createObj !!props)
      static member inline muiStepConnector(props: IReactProperty list) : IThemeProp = unbox ("props.MuiStepConnector", createObj !!props)
      static member inline muiStepContent(props: IReactProperty list) : IThemeProp = unbox ("props.MuiStepContent", createObj !!props)
      static member inline muiStepIcon(props: IReactProperty list) : IThemeProp = unbox ("props.MuiStepIcon", createObj !!props)
      static member inline muiStepLabel(props: IReactProperty list) : IThemeProp = unbox ("props.MuiStepLabel", createObj !!props)
      static member inline muiStepper(props: IReactProperty list) : IThemeProp = unbox ("props.MuiStepper", createObj !!props)
      static member inline muiSvgIcon(props: IReactProperty list) : IThemeProp = unbox ("props.MuiSvgIcon", createObj !!props)
      static member inline muiSwipeableDrawer(props: IReactProperty list) : IThemeProp = unbox ("props.MuiSwipeableDrawer", createObj !!props)
      static member inline muiSwitch(props: IReactProperty list) : IThemeProp = unbox ("props.MuiSwitch", createObj !!props)
      static member inline muiTab(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTab", createObj !!props)
      static member inline muiTabContext(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTabContext", createObj !!props)
      static member inline muiTable(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTable", createObj !!props)
      static member inline muiTableBody(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTableBody", createObj !!props)
      static member inline muiTableCell(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTableCell", createObj !!props)
      static member inline muiTableContainer(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTableContainer", createObj !!props)
      static member inline muiTableFooter(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTableFooter", createObj !!props)
      static member inline muiTableHead(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTableHead", createObj !!props)
      static member inline muiTablePagination(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTablePagination", createObj !!props)
      static member inline muiTableRow(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTableRow", createObj !!props)
      static member inline muiTableSortLabel(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTableSortLabel", createObj !!props)
      static member inline muiTabList(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTabList", createObj !!props)
      static member inline muiTabPanel(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTabPanel", createObj !!props)
      static member inline muiTabs(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTabs", createObj !!props)
      static member inline muiTabScrollButton(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTabScrollButton", createObj !!props)
      static member inline muiTextareaAutosize(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTextareaAutosize", createObj !!props)
      static member inline muiTextField(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTextField", createObj !!props)
      static member inline muiTimeline(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTimeline", createObj !!props)
      static member inline muiTimelineConnector(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTimelineConnector", createObj !!props)
      static member inline muiTimelineContent(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTimelineContent", createObj !!props)
      static member inline muiTimelineDot(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTimelineDot", createObj !!props)
      static member inline muiTimelineItem(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTimelineItem", createObj !!props)
      static member inline muiTimelineOppositeContent(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTimelineOppositeContent", createObj !!props)
      static member inline muiTimelineSeparator(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTimelineSeparator", createObj !!props)
      static member inline muiToggleButton(props: IReactProperty list) : IThemeProp = unbox ("props.MuiToggleButton", createObj !!props)
      static member inline muiToggleButtonGroup(props: IReactProperty list) : IThemeProp = unbox ("props.MuiToggleButtonGroup", createObj !!props)
      static member inline muiToolbar(props: IReactProperty list) : IThemeProp = unbox ("props.MuiToolbar", createObj !!props)
      static member inline muiTooltip(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTooltip", createObj !!props)
      static member inline muiTreeItem(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTreeItem", createObj !!props)
      static member inline muiTreeView(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTreeView", createObj !!props)
      static member inline muiTypography(props: IReactProperty list) : IThemeProp = unbox ("props.MuiTypography", createObj !!props)
      static member inline muiUnstable_TrapFocus(props: IReactProperty list) : IThemeProp = unbox ("props.MuiUnstable_TrapFocus", createObj !!props)
      static member inline muiZoom(props: IReactProperty list) : IThemeProp = unbox ("props.MuiZoom", createObj !!props)
