namespace Feliz.MaterialUI

(*////////////////////////////////
/// THIS FILE IS AUTO-GENERATED //
////////////////////////////////*)

open System.ComponentModel
open Fable.Core
open Fable.Core.JsInterop
open Feliz


[<AutoOpen; EditorBrowsable(EditorBrowsableState.Never)>]
module themeProps =

  module theme =

    [<Erase>]
    type defaultProps =
      static member inline muiAccordion(props: IReactProperty list) : IThemeProp = unbox ("components.MuiAccordion.defaultProps", createObj !!props)
      static member inline muiAccordionActions(props: IReactProperty list) : IThemeProp = unbox ("components.MuiAccordionActions.defaultProps", createObj !!props)
      static member inline muiAccordionDetails(props: IReactProperty list) : IThemeProp = unbox ("components.MuiAccordionDetails.defaultProps", createObj !!props)
      static member inline muiAccordionSummary(props: IReactProperty list) : IThemeProp = unbox ("components.MuiAccordionSummary.defaultProps", createObj !!props)
      static member inline muiAlert(props: IReactProperty list) : IThemeProp = unbox ("components.MuiAlert.defaultProps", createObj !!props)
      static member inline muiAlertTitle(props: IReactProperty list) : IThemeProp = unbox ("components.MuiAlertTitle.defaultProps", createObj !!props)
      static member inline muiAppBar(props: IReactProperty list) : IThemeProp = unbox ("components.MuiAppBar.defaultProps", createObj !!props)
      static member inline muiAutocomplete(props: IReactProperty list) : IThemeProp = unbox ("components.MuiAutocomplete.defaultProps", createObj !!props)
      static member inline muiAvatar(props: IReactProperty list) : IThemeProp = unbox ("components.MuiAvatar.defaultProps", createObj !!props)
      static member inline muiAvatarGroup(props: IReactProperty list) : IThemeProp = unbox ("components.MuiAvatarGroup.defaultProps", createObj !!props)
      static member inline muiBackdrop(props: IReactProperty list) : IThemeProp = unbox ("components.MuiBackdrop.defaultProps", createObj !!props)
      static member inline muiBadge(props: IReactProperty list) : IThemeProp = unbox ("components.MuiBadge.defaultProps", createObj !!props)
      static member inline muiBottomNavigation(props: IReactProperty list) : IThemeProp = unbox ("components.MuiBottomNavigation.defaultProps", createObj !!props)
      static member inline muiBottomNavigationAction(props: IReactProperty list) : IThemeProp = unbox ("components.MuiBottomNavigationAction.defaultProps", createObj !!props)
      static member inline muiBox(props: IReactProperty list) : IThemeProp = unbox ("components.MuiBox.defaultProps", createObj !!props)
      static member inline muiBreadcrumbs(props: IReactProperty list) : IThemeProp = unbox ("components.MuiBreadcrumbs.defaultProps", createObj !!props)
      static member inline muiButton(props: IReactProperty list) : IThemeProp = unbox ("components.MuiButton.defaultProps", createObj !!props)
      static member inline muiButtonBase(props: IReactProperty list) : IThemeProp = unbox ("components.MuiButtonBase.defaultProps", createObj !!props)
      static member inline muiButtonGroup(props: IReactProperty list) : IThemeProp = unbox ("components.MuiButtonGroup.defaultProps", createObj !!props)
      static member inline muiCard(props: IReactProperty list) : IThemeProp = unbox ("components.MuiCard.defaultProps", createObj !!props)
      static member inline muiCardActionArea(props: IReactProperty list) : IThemeProp = unbox ("components.MuiCardActionArea.defaultProps", createObj !!props)
      static member inline muiCardActions(props: IReactProperty list) : IThemeProp = unbox ("components.MuiCardActions.defaultProps", createObj !!props)
      static member inline muiCardContent(props: IReactProperty list) : IThemeProp = unbox ("components.MuiCardContent.defaultProps", createObj !!props)
      static member inline muiCardHeader(props: IReactProperty list) : IThemeProp = unbox ("components.MuiCardHeader.defaultProps", createObj !!props)
      static member inline muiCardMedia(props: IReactProperty list) : IThemeProp = unbox ("components.MuiCardMedia.defaultProps", createObj !!props)
      static member inline muiCheckbox(props: IReactProperty list) : IThemeProp = unbox ("components.MuiCheckbox.defaultProps", createObj !!props)
      static member inline muiChip(props: IReactProperty list) : IThemeProp = unbox ("components.MuiChip.defaultProps", createObj !!props)
      static member inline muiCircularProgress(props: IReactProperty list) : IThemeProp = unbox ("components.MuiCircularProgress.defaultProps", createObj !!props)
      static member inline muiCollapse(props: IReactProperty list) : IThemeProp = unbox ("components.MuiCollapse.defaultProps", createObj !!props)
      static member inline muiContainer(props: IReactProperty list) : IThemeProp = unbox ("components.MuiContainer.defaultProps", createObj !!props)
      static member inline muiCssBaseline(props: IReactProperty list) : IThemeProp = unbox ("components.MuiCssBaseline.defaultProps", createObj !!props)
      static member inline muiDialog(props: IReactProperty list) : IThemeProp = unbox ("components.MuiDialog.defaultProps", createObj !!props)
      static member inline muiDialogActions(props: IReactProperty list) : IThemeProp = unbox ("components.MuiDialogActions.defaultProps", createObj !!props)
      static member inline muiDialogContent(props: IReactProperty list) : IThemeProp = unbox ("components.MuiDialogContent.defaultProps", createObj !!props)
      static member inline muiDialogContentText(props: IReactProperty list) : IThemeProp = unbox ("components.MuiDialogContentText.defaultProps", createObj !!props)
      static member inline muiDialogTitle(props: IReactProperty list) : IThemeProp = unbox ("components.MuiDialogTitle.defaultProps", createObj !!props)
      static member inline muiDivider(props: IReactProperty list) : IThemeProp = unbox ("components.MuiDivider.defaultProps", createObj !!props)
      static member inline muiDrawer(props: IReactProperty list) : IThemeProp = unbox ("components.MuiDrawer.defaultProps", createObj !!props)
      static member inline muiFab(props: IReactProperty list) : IThemeProp = unbox ("components.MuiFab.defaultProps", createObj !!props)
      static member inline muiFade(props: IReactProperty list) : IThemeProp = unbox ("components.MuiFade.defaultProps", createObj !!props)
      static member inline muiFilledInput(props: IReactProperty list) : IThemeProp = unbox ("components.MuiFilledInput.defaultProps", createObj !!props)
      static member inline muiFormControl(props: IReactProperty list) : IThemeProp = unbox ("components.MuiFormControl.defaultProps", createObj !!props)
      static member inline muiFormControlLabel(props: IReactProperty list) : IThemeProp = unbox ("components.MuiFormControlLabel.defaultProps", createObj !!props)
      static member inline muiFormGroup(props: IReactProperty list) : IThemeProp = unbox ("components.MuiFormGroup.defaultProps", createObj !!props)
      static member inline muiFormHelperText(props: IReactProperty list) : IThemeProp = unbox ("components.MuiFormHelperText.defaultProps", createObj !!props)
      static member inline muiFormLabel(props: IReactProperty list) : IThemeProp = unbox ("components.MuiFormLabel.defaultProps", createObj !!props)
      static member inline muiGlobalStyles(props: IReactProperty list) : IThemeProp = unbox ("components.MuiGlobalStyles.defaultProps", createObj !!props)
      static member inline muiGrid(props: IReactProperty list) : IThemeProp = unbox ("components.MuiGrid.defaultProps", createObj !!props)
      static member inline muiGrow(props: IReactProperty list) : IThemeProp = unbox ("components.MuiGrow.defaultProps", createObj !!props)
      static member inline muiHidden(props: IReactProperty list) : IThemeProp = unbox ("components.MuiHidden.defaultProps", createObj !!props)
      static member inline muiIcon(props: IReactProperty list) : IThemeProp = unbox ("components.MuiIcon.defaultProps", createObj !!props)
      static member inline muiIconButton(props: IReactProperty list) : IThemeProp = unbox ("components.MuiIconButton.defaultProps", createObj !!props)
      static member inline muiImageList(props: IReactProperty list) : IThemeProp = unbox ("components.MuiImageList.defaultProps", createObj !!props)
      static member inline muiImageListItem(props: IReactProperty list) : IThemeProp = unbox ("components.MuiImageListItem.defaultProps", createObj !!props)
      static member inline muiImageListItemBar(props: IReactProperty list) : IThemeProp = unbox ("components.MuiImageListItemBar.defaultProps", createObj !!props)
      static member inline muiInput(props: IReactProperty list) : IThemeProp = unbox ("components.MuiInput.defaultProps", createObj !!props)
      static member inline muiInputAdornment(props: IReactProperty list) : IThemeProp = unbox ("components.MuiInputAdornment.defaultProps", createObj !!props)
      static member inline muiInputBase(props: IReactProperty list) : IThemeProp = unbox ("components.MuiInputBase.defaultProps", createObj !!props)
      static member inline muiInputLabel(props: IReactProperty list) : IThemeProp = unbox ("components.MuiInputLabel.defaultProps", createObj !!props)
      static member inline muiLinearProgress(props: IReactProperty list) : IThemeProp = unbox ("components.MuiLinearProgress.defaultProps", createObj !!props)
      static member inline muiLink(props: IReactProperty list) : IThemeProp = unbox ("components.MuiLink.defaultProps", createObj !!props)
      static member inline muiList(props: IReactProperty list) : IThemeProp = unbox ("components.MuiList.defaultProps", createObj !!props)
      static member inline muiListItem(props: IReactProperty list) : IThemeProp = unbox ("components.MuiListItem.defaultProps", createObj !!props)
      static member inline muiListItemAvatar(props: IReactProperty list) : IThemeProp = unbox ("components.MuiListItemAvatar.defaultProps", createObj !!props)
      static member inline muiListItemButton(props: IReactProperty list) : IThemeProp = unbox ("components.MuiListItemButton.defaultProps", createObj !!props)
      static member inline muiListItemIcon(props: IReactProperty list) : IThemeProp = unbox ("components.MuiListItemIcon.defaultProps", createObj !!props)
      static member inline muiListItemSecondaryAction(props: IReactProperty list) : IThemeProp = unbox ("components.MuiListItemSecondaryAction.defaultProps", createObj !!props)
      static member inline muiListItemText(props: IReactProperty list) : IThemeProp = unbox ("components.MuiListItemText.defaultProps", createObj !!props)
      static member inline muiListSubheader(props: IReactProperty list) : IThemeProp = unbox ("components.MuiListSubheader.defaultProps", createObj !!props)
      static member inline muiLoadingButton(props: IReactProperty list) : IThemeProp = unbox ("components.MuiLoadingButton.defaultProps", createObj !!props)
      static member inline muiMasonry(props: IReactProperty list) : IThemeProp = unbox ("components.MuiMasonry.defaultProps", createObj !!props)
      static member inline muiMenu(props: IReactProperty list) : IThemeProp = unbox ("components.MuiMenu.defaultProps", createObj !!props)
      static member inline muiMenuItem(props: IReactProperty list) : IThemeProp = unbox ("components.MuiMenuItem.defaultProps", createObj !!props)
      static member inline muiMenuList(props: IReactProperty list) : IThemeProp = unbox ("components.MuiMenuList.defaultProps", createObj !!props)
      static member inline muiMobileStepper(props: IReactProperty list) : IThemeProp = unbox ("components.MuiMobileStepper.defaultProps", createObj !!props)
      static member inline muiModal(props: IReactProperty list) : IThemeProp = unbox ("components.MuiModal.defaultProps", createObj !!props)
      static member inline muiNativeSelect(props: IReactProperty list) : IThemeProp = unbox ("components.MuiNativeSelect.defaultProps", createObj !!props)
      static member inline muiOutlinedInput(props: IReactProperty list) : IThemeProp = unbox ("components.MuiOutlinedInput.defaultProps", createObj !!props)
      static member inline muiPagination(props: IReactProperty list) : IThemeProp = unbox ("components.MuiPagination.defaultProps", createObj !!props)
      static member inline muiPaginationItem(props: IReactProperty list) : IThemeProp = unbox ("components.MuiPaginationItem.defaultProps", createObj !!props)
      static member inline muiPaper(props: IReactProperty list) : IThemeProp = unbox ("components.MuiPaper.defaultProps", createObj !!props)
      static member inline muiPopover(props: IReactProperty list) : IThemeProp = unbox ("components.MuiPopover.defaultProps", createObj !!props)
      static member inline muiPopper(props: IReactProperty list) : IThemeProp = unbox ("components.MuiPopper.defaultProps", createObj !!props)
      static member inline muiRadio(props: IReactProperty list) : IThemeProp = unbox ("components.MuiRadio.defaultProps", createObj !!props)
      static member inline muiRadioGroup(props: IReactProperty list) : IThemeProp = unbox ("components.MuiRadioGroup.defaultProps", createObj !!props)
      static member inline muiRating(props: IReactProperty list) : IThemeProp = unbox ("components.MuiRating.defaultProps", createObj !!props)
      static member inline muiScopedCssBaseline(props: IReactProperty list) : IThemeProp = unbox ("components.MuiScopedCssBaseline.defaultProps", createObj !!props)
      static member inline muiSelect(props: IReactProperty list) : IThemeProp = unbox ("components.MuiSelect.defaultProps", createObj !!props)
      static member inline muiSkeleton(props: IReactProperty list) : IThemeProp = unbox ("components.MuiSkeleton.defaultProps", createObj !!props)
      static member inline muiSlide(props: IReactProperty list) : IThemeProp = unbox ("components.MuiSlide.defaultProps", createObj !!props)
      static member inline muiSlider(props: IReactProperty list) : IThemeProp = unbox ("components.MuiSlider.defaultProps", createObj !!props)
      static member inline muiSnackbar(props: IReactProperty list) : IThemeProp = unbox ("components.MuiSnackbar.defaultProps", createObj !!props)
      static member inline muiSnackbarContent(props: IReactProperty list) : IThemeProp = unbox ("components.MuiSnackbarContent.defaultProps", createObj !!props)
      static member inline muiSpeedDial(props: IReactProperty list) : IThemeProp = unbox ("components.MuiSpeedDial.defaultProps", createObj !!props)
      static member inline muiSpeedDialAction(props: IReactProperty list) : IThemeProp = unbox ("components.MuiSpeedDialAction.defaultProps", createObj !!props)
      static member inline muiSpeedDialIcon(props: IReactProperty list) : IThemeProp = unbox ("components.MuiSpeedDialIcon.defaultProps", createObj !!props)
      static member inline muiStack(props: IReactProperty list) : IThemeProp = unbox ("components.MuiStack.defaultProps", createObj !!props)
      static member inline muiStep(props: IReactProperty list) : IThemeProp = unbox ("components.MuiStep.defaultProps", createObj !!props)
      static member inline muiStepButton(props: IReactProperty list) : IThemeProp = unbox ("components.MuiStepButton.defaultProps", createObj !!props)
      static member inline muiStepConnector(props: IReactProperty list) : IThemeProp = unbox ("components.MuiStepConnector.defaultProps", createObj !!props)
      static member inline muiStepContent(props: IReactProperty list) : IThemeProp = unbox ("components.MuiStepContent.defaultProps", createObj !!props)
      static member inline muiStepIcon(props: IReactProperty list) : IThemeProp = unbox ("components.MuiStepIcon.defaultProps", createObj !!props)
      static member inline muiStepLabel(props: IReactProperty list) : IThemeProp = unbox ("components.MuiStepLabel.defaultProps", createObj !!props)
      static member inline muiStepper(props: IReactProperty list) : IThemeProp = unbox ("components.MuiStepper.defaultProps", createObj !!props)
      static member inline muiSvgIcon(props: IReactProperty list) : IThemeProp = unbox ("components.MuiSvgIcon.defaultProps", createObj !!props)
      static member inline muiSwipeableDrawer(props: IReactProperty list) : IThemeProp = unbox ("components.MuiSwipeableDrawer.defaultProps", createObj !!props)
      static member inline muiSwitch(props: IReactProperty list) : IThemeProp = unbox ("components.MuiSwitch.defaultProps", createObj !!props)
      static member inline muiTab(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTab.defaultProps", createObj !!props)
      static member inline muiTabContext(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTabContext.defaultProps", createObj !!props)
      static member inline muiTable(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTable.defaultProps", createObj !!props)
      static member inline muiTableBody(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTableBody.defaultProps", createObj !!props)
      static member inline muiTableCell(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTableCell.defaultProps", createObj !!props)
      static member inline muiTableContainer(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTableContainer.defaultProps", createObj !!props)
      static member inline muiTableFooter(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTableFooter.defaultProps", createObj !!props)
      static member inline muiTableHead(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTableHead.defaultProps", createObj !!props)
      static member inline muiTablePagination(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTablePagination.defaultProps", createObj !!props)
      static member inline muiTableRow(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTableRow.defaultProps", createObj !!props)
      static member inline muiTableSortLabel(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTableSortLabel.defaultProps", createObj !!props)
      static member inline muiTabList(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTabList.defaultProps", createObj !!props)
      static member inline muiTabPanel(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTabPanel.defaultProps", createObj !!props)
      static member inline muiTabs(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTabs.defaultProps", createObj !!props)
      static member inline muiTabScrollButton(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTabScrollButton.defaultProps", createObj !!props)
      static member inline muiTextField(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTextField.defaultProps", createObj !!props)
      static member inline muiTimeline(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTimeline.defaultProps", createObj !!props)
      static member inline muiTimelineConnector(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTimelineConnector.defaultProps", createObj !!props)
      static member inline muiTimelineContent(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTimelineContent.defaultProps", createObj !!props)
      static member inline muiTimelineDot(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTimelineDot.defaultProps", createObj !!props)
      static member inline muiTimelineItem(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTimelineItem.defaultProps", createObj !!props)
      static member inline muiTimelineOppositeContent(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTimelineOppositeContent.defaultProps", createObj !!props)
      static member inline muiTimelineSeparator(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTimelineSeparator.defaultProps", createObj !!props)
      static member inline muiToggleButton(props: IReactProperty list) : IThemeProp = unbox ("components.MuiToggleButton.defaultProps", createObj !!props)
      static member inline muiToggleButtonGroup(props: IReactProperty list) : IThemeProp = unbox ("components.MuiToggleButtonGroup.defaultProps", createObj !!props)
      static member inline muiToolbar(props: IReactProperty list) : IThemeProp = unbox ("components.MuiToolbar.defaultProps", createObj !!props)
      static member inline muiTooltip(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTooltip.defaultProps", createObj !!props)
      static member inline muiTreeItem(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTreeItem.defaultProps", createObj !!props)
      static member inline muiTreeView(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTreeView.defaultProps", createObj !!props)
      static member inline muiTypography(props: IReactProperty list) : IThemeProp = unbox ("components.MuiTypography.defaultProps", createObj !!props)
      static member inline muiZoom(props: IReactProperty list) : IThemeProp = unbox ("components.MuiZoom.defaultProps", createObj !!props)
